/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "RTOS_Scheduler.h"
#include "STM32F103x6_GPIO_Driver.h"


RTOS_TaskConfig_t Task1, Task2, Task3;
uint32_t Task1LED, Task2LED, Task3LED;

void ToggleTaskLED(uint32_t* TaskLED, uint32_t Count)
{
	uint32_t i = 0;
	while(i < Count)
	{
		*TaskLED ^= 1;
		i++;
	}
}


void Task1Func(void)
{
	while(1){
		ToggleTaskLED(&Task1LED, 100);
		anaRTOS_TerminateTask(&Task1);
	}
}
void Task2Func(void)
{
	while(1){
		ToggleTaskLED(&Task2LED, 100);
		anaRTOS_TerminateTask(&Task2);
		ToggleTaskLED(&Task2LED, 100);
		anaRTOS_ActivateTask(&Task1);

	}
}
void Task3Func(void)
{
	while(1){
		ToggleTaskLED(&Task3LED, 200);
		anaRTOS_ActivateTask(&Task2);
	}
}


int main(void)
{
	anaRTOS_Init();

	strcpy(Task1.TaskUserConfig.Task_Name, "Task 1");
	Task1.TaskUserConfig.Task_InputPriority = 0;	// High priority
	Task1.TaskUserConfig.Task_ProgramEntry = &Task1Func;
	Task1.TaskUserConfig.Task_StackSize = 100;	// 100 Bytes
	anaRTOS_CreateTask(&Task1);

	strcpy(Task2.TaskUserConfig.Task_Name, "Task 2");
	Task2.TaskUserConfig.Task_InputPriority = 1;	// Medium priority
	Task2.TaskUserConfig.Task_ProgramEntry = &Task2Func;
	Task2.TaskUserConfig.Task_StackSize = 100;	// 100 Bytes
	anaRTOS_CreateTask(&Task2);

	strcpy(Task3.TaskUserConfig.Task_Name, "Task 3");
	Task3.TaskUserConfig.Task_InputPriority = 2;	// Low priority
	Task3.TaskUserConfig.Task_ProgramEntry = &Task3Func;
	Task3.TaskUserConfig.Task_StackSize = 100;	// 100 Bytes
	anaRTOS_CreateTask(&Task3);

	anaRTOS_ActivateTask(&Task1);
	anaRTOS_ActivateTask(&Task2);
	anaRTOS_ActivateTask(&Task3);

	RTOS_HW_init();

	anaRTOS_StartOS();

	while(1)
	{
	}
}


